name: The Unapologetic Texan
favicon: null
layout_spectrum: 0.1134085
typography_spectrum: 0.5238096
title: The Unapologetic Texan
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-27586538-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1217471261043102
  lightness: 0.03340730536729097
  saturation: 0.2623555702157319
  rhythmicContrast: 0.07801022683270276
purpose: []
