name: A Texanist Retrospective
favicon: null
layout_spectrum: 0.0034719721879810095
typography_spectrum: 0.5751174131873995
title: A Texanist Retrospective
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.12174712610431015
  lightness: 0.033407305367290974
  saturation: 0.26235557021573186
  rhythmicContrast: 0.07801022683270276
purpose: []
